### ISSUE TITLE
/device?addr=IP does not filter by IP address

### ISSUE THREAD

**Issue by tgru** [OpenXbox/xbox-smartglass-rest-python#23]
**Observed behavior**: All Xbox One devices in the network get listed, if `/device?addr=IP` is used

**Expected behavior**: Only the device with the specified IP address get shown, like said in the README file:

> `# NOTE: You can enumerate device by specific ip: /device?addr=192.168.0.123`

**Environment**:
* Ubuntu 17.10
* Python 3.6.3

**Comment by tuxuser** [comment]
It is actually expected behaviour: The additional `addr` query is ment for situations where multicast traffic is not supported in your network configuration. This way you can *additionally* query a specific console by its IP address - the regular multicast/broadcast discovery happens too tho. That's why you see the other consoles on your net too. 


Suggestion: Additionally filter the dict for the IP address that you asked for

**Comment by tgru** [comment]
Thank you for the clarification. If thats the case the documentation should be more precise about this.

**Comment by tuxuser** [comment]
I decided to implement the filtering with commit facb77f Filter returned consoles when addr-query is supplied.

That way the rest server still has all discovered consoles cached but will return only the specific one if addr-query is supplied.
